config/routes.rb
Jerky::Application.routes.draw do

  root to: 'products#index'
  resources :products
  devise_for :users
  devise_scope :user do
    get 'login', :to => "devise/sessions#create"
    get 'logout', :to => "devise/sessions#destroy"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :price
  has_many :order_products
  has_many :orders, through: :order_products

  paginates_per 10
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  # has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @products = Product.order(sort_column + " " + sort_direction).page params[:page]
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      flsah[:notice] = "successfully created product"
      redirect_to @product
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  private

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "About 12 Days Project", 'http://12days.github.io' %></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sign in", login_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || Jerky %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/products/index.html.erb
<br><br>
<div class="row-fluid">

  <div class="span4">
    <%= paginate @products %>

    <table class="pretty">
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= "description" %></th>
        <th><%= sortable 'price' %></th>
      </tr>

      <% for jerky in @products %>
      <tr>
        <td><%= link_to jerky.name, product_path(jerky) %><br></td>
        <td><%= jerky.description %><br></td>
        <td class="price"><%= jerky.price %><br></td>
      </tr>
      <% end %>
    </table>

  <br>
  <p><%= link_to "new product", new_product_path %></p>
  </div>

  <div class="span8">
    <h3>The latest and greatest</h3>
    <div class="thumnails">
      <img alt="the biggest jerk!" style="width: 300px; height: 300px" src="../../assets/images/jerky300x300.jpg">
    </div>
  </div>


</div>

app/views/products/new.html.erb
<div class="hero-unit">

  try a jerky today!

  <br>
  <%= link_to 'back home', root_path %>
</div>

app/views/products/show.html.erb
<div class="hero-unit">
  <%= "Jerky name: #{@product.name}" %><br>
  <%= "Details: #{@product.description}" %><br>
  <%= "Bargain price: #{@product.price}" %><br><br>

  <%= link_to "back home", root_path %>
</div>